name: CI - PHPStan, CS Fixer, Codeception

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_sqlite

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run PHPStan static analysis
        run: vendor/bin/phpstan analyse -c phpstan.neon

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run Codeception tests with coverage
        run: vendor/bin/codecept run --coverage --coverage-xml

      - name: Verify coverage is above 80%
        run: |
          php -r " \
          \$xml = simplexml_load_file('tests/_output/coverage.xml'); \
          \$metrics = \$xml->project['metrics']; \
          \$covered = (int) \$metrics['coveredstatements']; \
          \$total = (int) \$metrics['statements']; \
          \$coverage = (\$total > 0) ? (\$covered / \$total) * 100 : 0; \
          echo 'Coverage: ' . round(\$coverage, 2) . \"%\n\"; \
          if (\$coverage < 80) { fwrite(STDERR, 'ERROR: Code coverage below 80%\n'); exit(1); }"
